export const TOTAL_EXPENSES = "общие расходы в галактических кредитах"
export const CIVILIZATION_WITH_MIN_EXPENSES = "цивилизация с минимальными расходами"
export const AMOUNT_OF_PROCESSED_ENTRIES = "количество обработанных записей"
export const DAY_WITH_MAX_EXPENSES = "день года с максимальными расходами"
export const DAY_WITH_MIN_EXPENSES = "день года с минимальными расходами"
export const MAX_EXPENSES_IN_ONE_DAY = "максимальная сумма расходов за день"
export const CIVILIZATION_WITH_MAX_EXPENSES = "цивилизация с максимальными расходами"
export const AVERAGE_EXPENSES = "средние расходы в галактических кредитах"